curve(from=-40, to=40, dnorm(x, mean=0, sd=10), xaxt="n", yaxt="n",ylab="", xlab="", col="red", ylim=c(0.0,0.04), lty=1, lwd=4, font.lab=2, "xaxs"="i" ,"yaxs"="i", bty="l", sub="Abb. 5: Signifikanzniveau und \u00DCberschreitungswahrscheinlichkeit bei G\u00FCltigkeit der H_0")
abline(v=22, col="black", lwd=3, lty=2)
text(23.75, 0.0012, expression(P), col = "black", cex=1.2)
abline(v=18, col="black", lwd=3)
text(20, 0.0018, expression(alpha), col = "black", cex=1.7)
axis( side=1, at=c(22, 18), labels=c("v", "c"), tick=FALSE)
axis( side=2, at=c(0.039), labels=c("f(v)"), tick=FALSE)
