browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/chi2_coefficients/example_chi2coeff.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/chi2_independence_test/example_indep.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/covariance/example_covariance.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/fishers_test/example_fisher.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/goodman_kruskal_lambda/example_gkl.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/goodman_kruskal_tau/example_gkt.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/mcnemar_test/example_mcnemar.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/somers_d/example_somerd.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/spearman_rank_test/example_spearman.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/spearman_rank_test/permutation_spearman.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/bivariate/steiger_z_test/example_steiger.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/1R/example_rpart1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/1R/RCART3.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/chaid/example_chaid.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/construction/example_cart.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/construction/RCART1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/ensemble/example_randomforest.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/mincer/RCART3.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/mincer/RCART4.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/regression/example_prune.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/regression/example_rpartanova.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cart/selection/example_rpartclass.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/cluster_analysis/adjacency.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/cluster_choice/cluster_cv.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/cluster_choice/cluster_elbow.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/cluster_choice/example_cluster_number.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/cluster_visualization/example_clusplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/dbscan_cluster/example_dbscan.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/dendrogram/dendrogram.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/dendrogram/example_dendro.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/distance/example_distance.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/divisive_cluster/example_diana.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/divisive_cluster/Norm_diana.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/em_cluster/example_em.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/k_means/example_kmeans.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/k_means/example_kmeans1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/k_means/example_kmeans2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/k_means/example_kmeans3.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/k_means/kmeansstd.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/k_means/Norm_totvar.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/linkage/example_agglom.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/linkage/linkage.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/silhouette/example_silhouette.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/silhouette/norm_silhouette.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/similarity/example_dist2simil.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/similarity/example_simil.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/two_step_cluster/example_mixed_clustering.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/two_step_cluster/matching_matrix.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/cluster/two_step_cluster/Voronoi_diagram.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/efa/efa_extraction/example_efa_extraction.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/efa/efa_rotation/example_efa_rotation.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/efa/efa_rotation/factor_rotation.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/efa/efa_rotation/rotation.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/efa/efa_scores/example_efa_scores.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/efa/efa_suitability/example_efa_suitability.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/efa/efa_suitability/helper.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/efa/efa_zhou/zhou_scree.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/g_test/example_gtest.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/goodman_kruskal_gamma/example_GKgamma.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/3d_graphs/example_3dscatter.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/andrews_curve/andrews_proj.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/andrews_curve/andrews.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/andrews_curve/example_andrews.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/average_shifted_histogram/ash.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/average_shifted_histogram/example_ash.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_grouped/barchart_grouped.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_grouped/example_barchart_grouped_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_grouped/example_barchart_grouped_graphics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_grouped/example_barchart_grouped_lattice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_grouped/example_barchart_grouped.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_stacked/barchart_stacked.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_stacked/example_barchart_stacked_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_stacked/example_barchart_stacked_graphics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_stacked/example_barchart_stacked_lattice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart_stacked/example_barchart_stacked.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart/barchart_example_barplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart/barchart_example_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart/barchart_example_lattice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart/barchart_example_plot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart/barchart_example1.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart/barchart_example2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/bar_chart/barchart.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/boxplot/boxplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/boxplot/example_boxplot_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/boxplot/example_boxplot_graphics.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/boxplot/example_boxplot_lattice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/boxplot/example_boxplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/errorbar/example_plotmeans.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/faces/example_faces.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/faces/faces.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/heatmap/example_heatmap1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/heatmap/example_heatmap2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/heatmap/heatmap.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/histogram/example_histogram_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/histogram/example_histogram_graphics.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/histogram/example_histogram_lattice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/histogram/example_histogram.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/histogram/histogram_example2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/histogram/histogram.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_conditional/cdplot.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_conditional/example_cdplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_conditional/example_sm_density_compare.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_estimator/example_kde_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_estimator/example_kde_graphics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_estimator/example_kde_lattice.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_estimator/example_kde.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_estimator/example_kdeh_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_estimator/example_kdeh_graphics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_estimator/example_kdeh_lattice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_estimator/kernel_function.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/kernel_density_estimator/KernelDensity.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/mosaicplot/example_mosaic_cotabplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/mosaicplot/example_mosaic_graphics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/mosaicplot/example_mosaic_plot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/mosaicplot/example_mosaic_vcd.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/mosaicplot/example_mosaic.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/mosaicplot/mosaic.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/parallel_coordinates/example_pcp_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/parallel_coordinates/example_pcp_graphics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/parallel_coordinates/example_pcp_lattice.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/parallel_coordinates/example_pcp.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/parallel_coordinates/pcp_correlation.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/parallel_coordinates/point_line_duality.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/pie_chart/example_piechart_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/pie_chart/example_piechart_graphics.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/pie_chart/example_piechart.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/pie_chart/piechart.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/ppplot/pplot0.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/ppplot/ppplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/pyramid/example_pyramid.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/pyramid/pyramid.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/example_qqplot_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/example_qqplot_graphics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/example_qqplot_lattice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/example_qqplot.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/example_qqplot1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/example_qqplot2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/qq_idea.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/qq.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/qqplot.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/qqplot/qqsamples.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/radar_chart/example_radar.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/radar_chart/radar.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/scatterplot_matrix/example_splom_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/scatterplot_matrix/example_splom_graphics.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/scatterplot_matrix/example_splom.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/scatterplot/BostonHousing.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/scatterplot/example_scatterplot2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/scatterplot/map_boston.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/scatterplot/scatterplot_example.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/stem_and_leaf/example_stem.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/strip_chart/example_stripchart_ggplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/strip_chart/example_stripchart_graphics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/strip_chart/example_stripchart_lattice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/strip_chart/example_stripchart.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/strip_chart/stripchart.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/sunflowerplot/example_sunflower.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/sunflowerplot/sunflower.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/trellis_display/example_trellis_boxplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/trellis_display/example_trellis_xyplot.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/trellis_display/example_trellis_xyplot2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/trellis_display/example_trellis.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/trellis_display/trellis.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/violin_plot/example_violin.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/graphics/violin_plot/violin.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/interactive_graphics/example_ggobi.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/breusch_pagan_test/example_bptest.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/cook_distance/example_cook.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/cook_distance/pic_confell_lm.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/durbin_watson_test/example_dwtest.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/leverage/example_leverage.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_anscombe/anscombe.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_coeff_standard/example_beta.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_coeff_test/example_bootcase.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_coeff/regression_plot.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_coeff/regression_simple.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_differences/example_diffbeta.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_model_selection/example_elasticnet.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_model_selection/example_lasso.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_model_selection/example_ridge.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_model_selection/example_step_aic.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_model_selection/example_step_f.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_model_selection/interpolation.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_model_selection/model_inout.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_model_selection/ridge_regression.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_predictor/predictor.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/linreg_residuals/regression_residuals.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/linreg/multicollinearity/example_multicollinearity.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/chained_equation/example_mice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/coding/example_na.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/create_mar.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/example_mar.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/exploratory/example_miss_explore.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/exploratory/example_miss_gui.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/exploratory/example_miss_missmap.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/imputation/example_impute1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/imputation/example_missing.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/mi/example_mi.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/norm/example_amelia.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/schafer/example_impute1.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/schafer/example_schafer1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/missing/types/missing2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nnet/activation/activation.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nnet/error/earlystopping.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nnet/mincer/example_neuralnet.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nnet/mincer/example_nnet.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nnet/mincer/mincer_nnet.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/kerneldensity/example_kernel1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/kerneldensity/example_kernel2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/kerneldensity/histogram.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/kerneldensity/kde.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/kerneldensity/kdeexam.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/nadarayawatson/example_nw1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/nadarayawatson/example_nw2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/nadarayawatson/nw.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/example_bmw2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/example_gam2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/example_lm2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/example_nw2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/example_plm2.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/example_ppr.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/example_sim.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/mincer.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/nw.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/nonpara/regressions/plotContour.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/boxplot/boxplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/boxplot/example_boxplot_outliers.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/dixonr/example_dixonr.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/grubbs_beck_test/example_grubbs_beck.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/grubbs_test/example_grubbs.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/mahalanobis/example_mahalanobis.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/mahalanobis/mahalanobis.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/outlyingness/example_stahel_donoho.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/outlyingness/outlyingness.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/scaled_distance/norm_dist.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/stem_leaf/example_stem.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/walsh_test/example_walsh.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/outlier/walsh_test/example_walsh2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/best_line/server.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/best_line/ui.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/component_choice/scree.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/component_interpret/pca_corr.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/components/example_pca.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/cov_cor/example_pca2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/cov_cor/pca_covcor.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/horn/example_paran.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/horn/horn.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/max_var/pca_proj.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/max_var/server.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/max_var/ui.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/reduction/server.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/pca/reduction/ui.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/components/example_install.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/data_ops/example_aggregate.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/data_ops/example_attach.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/data_ops/example_formula.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/data_ops/example_sort.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/graphs_create/example_annotation.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/graphs_create/example_scatterplot_3.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/graphs_create/example_scatterplot_ggplot.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/graphs_create/example_scatterplot_lattice.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/graphs_create/example_scatterplot_plot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/objects/example_access.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/objects/example_list.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/objects/example_matrix.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/objects/example_tibble.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/objects/example_vector.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/read_data/example_readspss.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/R/read_data/example_readxlsx.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/random_number/example_randu.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/regression/regression_model/regrmodel.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/reliability/cronbach_alpha/cronbachalpha.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/reliability/cronbach_alpha/example_reliability.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/reliability/reliability_coeff/example_splithalf.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/reliability/tukey_additivity_test/example_additivity_test.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/scagnostics/example_scagnostics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/scagnostics/scagnostics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/software/example_data_format.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/software/example_data_format1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/software/regression/regression_model/regrmodel.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/anova/example_anova.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/bonferroni_test/example_bonferroni.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/bonferroni/bonferroni.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/f_test/example_ftest.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/friedman/example_friedman.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/kruskal_wallis/example_kruskal_wallis.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/levene_test/example_levene.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/lsd_test/example_lsd.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/mann_whitney/example_mann_whitney.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/median_test/example_p_median_test.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/paired_ttest/example_paired_ttest.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/permutation_test/mannwhitneyu_r1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/permutation_test/mannwhitneyu.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/scheffe_test/example_scheffe.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/snk_duncan_test/example_snk_duncan.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/spreadlevel_plot/example_spreadlevel.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/spreadlevel_plot/spreadlevel.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/subgroup/subgroup_example.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/tukey_test/example_tukey.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/unpaired_ttest/twottest_example.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/subgroup/wilcoxon/example_wilcoxon.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/data_quality/example_tableplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/data_quality/tabplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/data_sampling/complexsample.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/data_sampling/sample.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/maximum_likelihood/example_holytrinity.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/maximum_likelihood/example_holytrinity2D.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/maximum_likelihood/HolyTrinity.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/maximum_likelihood/HolyTrinity2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/scaling/example_scales.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/scatterplot/example_scatterplot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/scatterplot/map_boston.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/statistical_tests/bootconf.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/statistical_tests/bootsample.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/statistical_tests/boottest.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/statistical_tests/exacttest.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/statistical_tests/example_boot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/statistical_tests/example_chisq.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/statistical_tests/fluctuation.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/theory/statistical_tests/pvalue.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/anderson_darling/example_ad.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/chi2gof/example_gof.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/cramer_von_mises/example_cvm.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/descriptive_summary/example_descriptive_summary.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/descriptive_summary/example_descriptive_table.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/dispersion/example_variance.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/ecdf/example_ecdf.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/ecdf/R-horsekick_grouped-ecdf.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/ecdf/R-horsekick_totals-ecdf.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/entropy/entropy.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/entropy/example_entropy.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/entropy/normentropy.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/impurity/example_impurity.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/impurity/gini.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/impurity/gini3.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/jarque_bera/example_jb.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/kstest/example_ks.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/kurtosis/example_kurtosis.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/location_coeff/example_location.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/location_coeff/modality.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/location_test/example_binomtest.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/location_test/example_median_test.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/location_test/example_onettest.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/location_test/example_signtest.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/location_test/tdist.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/moments/example_moments.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/quantile/example_quantile.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/quantile/quantile_conf.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/quantile/quantile.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/quantile/quartile_example.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/shapiro_wilk/example_shapiro.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/skewness/example_skewness.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/skewness/skewness.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/transformation/boxcox_yeo.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/transformation/example_boxcox.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/transformation/example_logit_boxcox.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/transformation/example_logit.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/transformation/example_scale_power.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/transformation/transformation.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=data/univariate/transformation/transinter.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=examples/info.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=examples/test_graphics.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=examples/test_output.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=noprg.R&W=480&H=480"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Additionssatz/Additionssatz.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Approximation/Approximation von Verteilungen.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/beispiel/info.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Binomialverteilung/Binomialverteilung.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/BravaisPearson/BravaisPearson.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Chi-Quadrat/Chi-Quadrat-Anpassung.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Chi-Quadrat/Chi-Quadrat-Verteilung.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Chi-Quadrat/Chi-Quadtat-Unabh.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_allbus.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Beispiel_allbus_Einkommen.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Beispiel_allbus_Geschlecht.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Beispiel_Benzin.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Beispiel_Berufe.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Beispiel_Haushalt_2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Beispiel_Haushalt.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Kreis.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Rechteck.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Saeule.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_Stab.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Eindimensional/Eindimensional_wages_Dot.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/EinseitigerTest/EinseitigerTest.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/EinseitigerTest/EinseitigerTestEntscheidung.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/EinseitigerTest/EinseitigerTestUeberschreitung.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Entscheidungssituationen/Entscheidungssituationen_Abb1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Entscheidungssituationen/Entscheidungssituationen_Abb2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Erwartungstreue/Erwartungstreue.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ExponentialV/Exponential_Dichte.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ExponentialV/Exponential_VerteilungF.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ExponentialV/Exponential_WahrD2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/F-Test/F-Verteilung.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Gauß-Test/Gauß-Test.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Gleichverteilung/Diskrete_Gleichverteilung_1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Gleichverteilung/Diskrete_Gleichverteilung_VerteilungF.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/GrundbegriffeSchaetztheorie/Schätzwerte_Haushalt_2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/GrundbegriffeSchaetztheorie/Schätzwerte_Haushalt_3_100.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/GrundbegriffeSchaetztheorie/Schätzwerte_Haushalt_4_100.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/GrundbegriffeSchaetztheorie/Schätzwerte_Haushalt.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Guetefunktion/GF_linksseitig.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Guetefunktion/GF_mu0_1000_4SP.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Guetefunktion/GF_mu0_1000.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Guetefunktion/GF_rechtsseitig.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Guetefunktion/GF_zweiseitig_2Alpha.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Guetefunktion/GF_zweiseitig_4SP.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Guetefunktion/GF_zweiseitig.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Guetefunktion/Verteilung_Teststatistik.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/GueteRegression/Scatterplot_Fahrzeuge.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/GueteRegression/Scatterplot_Kriminalität.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/GueteRegression/Zerlegung_1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/HypergeometrischeVerteilung/HypergeometrischeVerteilung.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/KendallscherRangkorrelationskoeffizient/Kendallscher Rangkorrelationskoeffizient.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Konfidenzintervall/Konfidenzintervall_varianz_bekannt.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Konfidenzintervall/Konfidenzintervall_varianz_unbekannt1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Konfidenzintervall/Konfidenzintervall_varianz_unbekannt2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/LineareRegression/Lineare_Regression_nichtlinear_residuen.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/LineareRegression/Lineare_Regression_residuen.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/LineareRegression/Lineare_Regression.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/LinearesRegressionsmodell/Lineares_Regressionsmodell.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Normalverteilung/Dichtefunktion_N2_1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Normalverteilung/Eigenschaften_Dichte.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Normalverteilung/Eigenschaften_Verteilung.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Normalverteilung/Normalverteilung_Dichte.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Normalverteilung/Verteilungsfunktion_N2_1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ParameterEindimensional/Parameter_Eindimensional.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/PeriodischeSchwankung/Decomposition_PKW.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/PeriodischeSchwankung/Zulassungszahl neuer PKW.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Poissonverteilung/Poisson_L1_L5.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Poissonverteilung/Wahrscheinlichkeitsfunktion_PO10.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Poissonverteilung/Wahrscheinlichkeitsfunktion_PO2.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Poissonverteilung/Wahrscheinlichkeitsfunktion_PO5.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Quartile/Darstellung_Quartile.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Quartile/Gluehlampen.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Randverteilung/Randverteilung_Dichte.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Randverteilung/Randverteilung_Grafik.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Randverteilung/Randverteilung_Wahrscheinlichkeitsfunktion.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/SchaetzungRegressionsparameter/Punktwolke.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/SchaetzungRegressionsparameter/Regression_Haushaltseinkommen.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/SchaetzungRegressionsparameter/Regressionsgleichung.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/SchaetzungRegressionsparameter/Scatterplot_Haushaltseinkommen.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/SchaetzungRegressionsparameter/Zweite_Bedingung.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Schwankungsintervall/Schwankungsintervall_N_100_10.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Schwankungsintervall/Schwankungsintervall_N.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Dichtefunktion_Interall_80_119.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Dichtefunktion_Intervall.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Dichtefunktion_max_107.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Dichtefunktion_max_125.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Dichtefunktion_max_80.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Dichtefunktion_min_115.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Dichtefunktion_min_118.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Dichtefunktion_min_94.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Dichtefunktion_N_0_1.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Standardnormalverteilung/Verteilungsfunktion_N_0_1.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Statistik/lottozahlen.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/StetigeGleichverteilung/Dichtefunktion_0_20.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/StetigeGleichverteilung/Dichtefunktion_SGV.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/StetigeGleichverteilung/Verteilungsfunktion_0_20.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/StetigeGleichverteilung/Verteilungsfunktion_SGV.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/t-Verteilung/Dichtefunktion.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/TestAnteilswert/Gütefunktion_linksseitig.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/TestAnteilswert/Gütefunktion_rechtsseitig.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Trend/Anzahl_Telefone.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Trend/Leistungsbilanzsalden.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/Trend/Zulassung_PKW.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ZweidimensionaleHaeufigkeit/3D_Balkendiagramm.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ZweidimensionaleHaeufigkeit/Barplot_Sportler.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ZweidimensionaleHaeufigkeit/Streuungsdiagramm_Mordrate-3D.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ZweidimensionaleHaeufigkeit/Streuungsdiagramm_Mordrate.R"); Sys.sleep(20)

browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ZweidimensionaleHaeufigkeit/Streuungsdiagramm-Matrix.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ZweidimensionaleHaeufigkeit/Streuungsdiagramm.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ZweidimensionaleHaeufigkeit/Streuungsdiagramm3D.R"); Sys.sleep(20)
browseURL("https://shinyapps.wiwi.hu-berlin.de/examples/?P=stat/ZweiseitigerTest/ZweiseitigerTest.R"); Sys.sleep(20)


