curve(from=-4, to=4, dnorm(x, mean=0, sd=1), xaxt="n", yaxt="n",ylab="", xlab="", col="red", ylim=c(0.0,0.4), lty=1, lwd=4, font.lab=2, "xaxs"="i" ,"yaxs"="i", bty="l", sub="Abb. 1: Verteilung der Teststatistik V unter H_0 und Entscheidungsbereiche")
abline(v=-2, col="black", lwd=2)
abline(v=2, col="black", lwd=2)
abline(v=0.0, col="black", lwd=4, lty=2)
text(0, 0.15, expression(paste("1-" , alpha,"=0,95")), col = "black", cex=1.7)
text(-2.7, 0.01, expression(paste(alpha, "/2=0,025")), col = "black", cex=1.2)
text(2.7, 0.01, expression(paste(alpha, "/2=0,025")), col = "black", cex=1.2)
axis( side=1, at=c(-2, 0, 2, 4), labels=c("-1,96", "0", "1,96", "v"), tick=FALSE, cex.axis=1.5)
axis( side=2, at=c(0.39), labels=c("f(v)"), tick=FALSE, cex.axis=1.5)
